# Generated by Django 3.2.5 on 2021-07-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objet',
            old_name='giving_date',
            new_name='sending_date',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='type',
        ),
        migrations.AddField(
            model_name='objet',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='objet',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateTimeField()),
                ('state', models.CharField(max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Objet_Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objet')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shipping')),
            ],
        ),
    ]
