# Generated by Django 3.2.5 on 2021-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_utilisateur_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet_shipping',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sending_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
